# This file gathers container configuration that must be loaded at the application level

parameters:
    security.authentication.listener.anonymous.class: Claroline\CoreBundle\Listener\AnonymousAuthenticationListener
    templating.locator.class: Claroline\CoreBundle\Library\Templating\Loader\TemplateLocator
    twig.controller.exception.class : Claroline\CoreBundle\Controller\CustomExceptionController
services:
    templating.locator:
        class: '%templating.locator.class%'
        arguments:
            - "@file_locator"
            - "@claroline.config.platform_config_handler"
            - "@claroline.common.theme_service"
            - %kernel.root_dir%/Resources
