zenstruck_form:
    form_types:
        theme:                  true
        ajax_entity:            true
        ajax_entity_controller: true
    theme_options:
        label_width:   col-md-3
        control_width: col-md-9
